version: '3.6'

services:

  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - 8080:8080
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL: 300
      HASURA_GRAPHQL_ADMIN_SECRET: pass
      HASURA_GRAPHQL_AUTH_HOOK: http://auth-server:4000
    depends_on:
      - postgres
      - auth-server

  auth-server:
    build:
      context: .
      dockerfile: ./services/auth-server/Dockerfile.dev
    volumes:
      - ./:/app
    restart: always
    ports:
      - 4000:4000
      - 9229:9229
    depends_on:
      - postgres

  html:
    build:
      context: .
      dockerfile: ./services/html/Dockerfile.dev
    volumes:
      - ./:/app
    restart: always
    ports:
      - 3000:3000
      - 9222:9222
    depends_on:
      - graphql-engine

volumes:
  db_data:
